### ISSUE TITLE
ActionButtonView Left and Right button margins are not working.

### ISSUE THREAD

**Issue by Druffl3** [cemozguraA/Xamarin.RisePlugin.Floatingactionbutton#1]
No matter what value I provide for Right and Left margin, it simply doesn't change anything.

Here's what I am trying:

```
var btn = new ActionButtonView() { BackgroundColor = Color.Aqua, SelectedColor = Color.Brown, HeightRequest = 50, Icon = "logo.png" };
btn.Margin = new Thickness(20, 10, 100, Device.RuntimePlatform == Device.Android ? 80 : 10);
COAFloatingactionbutton.Current.ActionOrientation = StackActionOrientation.Right;
COAFloatingactionbutton.Current.MainButtonView = btn;
COAFloatingactionbutton.Current.Open();
```

And this is my result:
![fab_right_issue](https://user-images.githubusercontent.com/28187687/98525229-36882000-229e-11eb-9275-abd1aff927ee.jpeg)

You can notice that there is no space to the right of the button.

**Comment by Druffl3** [comment]
The left and Right margin are actually not being consumed in [COAFloatingActionButton](https://github.com/cemozguraA/Xamarin.RisePlugin.Floatingactionbutton/blob/master/Xamarin.RisePlugin.Droid.Floatingactionbutton/COAFloatingactionbutton.cs#L47-L48)


```
lrparam.SetMargins(0, (int)MainButtonView.Margin.Top, 0, (int)MainButtonView.Margin.Bottom); linearLayout.LayoutParameters = lrparam;
```

**Comment by Druffl3** [comment]
Have submitted a [PR to fix this issue](https://github.com/cemozguraA/Xamarin.RisePlugin.Floatingactionbutton/pull/2).

**Comment by cemozguraA** [comment]
Sorry for my late answer, will be fixed as soon as possible

**Comment by Druffl3** [comment]
Hey, that's alright, I actually rer-submitted a PR here: #3

**Comment by OlegZhXam** [comment]
Hello there, thank you for this useful control! Is there any chance that the nuget package is updated to include this fix?
Thanks!

**Comment by cemozguraA** [comment]
I uploaded
